In [ ]:
import torch

In [ ]:
x = torch.tensor(3.0, requires_grad = True)

In [ ]:
y= x**2

In [ ]:
z= torch.sin(y)

In [ ]:
x

tensor(3., requires_grad=True)

In [ ]:
y

tensor(9., grad_fn=<PowBackward0>)

In [ ]:
z

tensor(0.4121, grad_fn=<SinBackward0>)

In [ ]:
z.backward()

In [ ]:
x.grad

tensor(-5.4668)

In [ ]:
a = torch.tensor([1.0,2.0,3.0], requires_grad=True)
a

tensor([1., 2., 3.], requires_grad=True)

In [ ]:
b = (a**2).mean()

In [ ]:
b.backward()

In [ ]:
print(a.grad)

tensor([0.6667, 1.3333, 2.0000])


In [ ]:
a.grad.zero_()

tensor([0., 0., 0.])

In [ ]:
a.requires_grad_(False)

tensor([1., 2., 3.])

In [ ]:
a

tensor([1., 2., 3.])

In [ ]:
x = torch.tensor(3.0, requires_grad = True)

In [ ]:
with torch.no_grad():
    y = x**2

In [ ]:
y

tensor(9.)

# Pytorch Training Pipeline


In [25]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [26]:
df = pd.read_csv("https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv")

In [27]:
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [28]:
 df.shape

(569, 33)

In [29]:
df.drop(columns = ['id',"Unnamed: 32"], inplace=True)

In [30]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

In [31]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,1:],df.iloc[:,0],test_size=0.2)

In [32]:
#scaling
sclaer = StandardScaler()
X_train = sclaer.fit_transform(X_train)
X_test = sclaer.transform(X_test)

In [33]:
X_train

array([[ 1.44799891,  1.22374462,  1.68484363, ...,  0.98323582,
         0.45035471,  1.01852527],
       [-0.87302327, -1.04067074, -0.90484011, ..., -1.11179048,
        -1.60252981, -0.58681769],
       [ 0.58442947,  0.49212975,  0.59383681, ...,  0.26994866,
         0.94021098, -0.41841353],
       ...,
       [-0.1471659 ,  1.19905823, -0.17403211, ...,  0.29659895,
         0.92409729, -0.26376787],
       [ 1.89556313,  2.64209002,  1.82226052, ...,  0.8139281 ,
        -0.04594705, -0.08875963],
       [ 1.95581216,  0.94546166,  1.95551326, ...,  1.51310629,
         0.36978624, -0.29183523]])

In [34]:
y_train

12     M
173    B
132    M
500    B
111    B
      ..
118    M
237    M
126    M
265    M
250    M
Name: diagnosis, Length: 455, dtype: object

In [35]:
#labelencoding
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [36]:
y_train

array([1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0,
       1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1,
       0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0,

Numpy array to pytorch tensors


In [37]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [38]:
X_train_tensor

tensor([[ 1.4480,  1.2237,  1.6848,  ...,  0.9832,  0.4504,  1.0185],
        [-0.8730, -1.0407, -0.9048,  ..., -1.1118, -1.6025, -0.5868],
        [ 0.5844,  0.4921,  0.5938,  ...,  0.2699,  0.9402, -0.4184],
        ...,
        [-0.1472,  1.1991, -0.1740,  ...,  0.2966,  0.9241, -0.2638],
        [ 1.8956,  2.6421,  1.8223,  ...,  0.8139, -0.0459, -0.0888],
        [ 1.9558,  0.9455,  1.9555,  ...,  1.5131,  0.3698, -0.2918]],
       dtype=torch.float64)

In [39]:
X_train_tensor.shape

torch.Size([455, 30])

In [59]:
#Defining Model
import torch
import torch.nn as nn

class SimpleNN(nn.Module):

  def __init__(self, num_features):
    super().__init__()
    self.linear = nn.Linear(num_features,1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):
    out = self.linear(features)
    out = self.sigmoid(out)
    return out



In [60]:
#params

learning_rate = 0.1
epochs = 25


In [61]:
loss_function = nn.BCELoss()

In [62]:
type(loss_function)

torch.nn.modules.loss.BCELoss

In [63]:
#training pipeline

#create model
model = SimpleNN(X_train_tensor.shape[1])

#defien optimizer
optimizer = torch.optim.SGD(model.parameters(), lr = learning_rate)

#define loop
for epoch in range(epochs):

  #forward pass
  y_pred = model(X_train_tensor.float()) # Change the data type of X_train_tensor to float

  # loss calculate
  loss = loss_function(y_pred, y_train_tensor.view(-1,1).float())

  #clear gradients
  optimizer.zero_grad()

  #backward pass
  loss.backward()

  #parameters update
  optimizer.step()

  #print loss
  print(f"Epoch: {epoch+1} Loss: {loss}")

Epoch: 1 Loss: 0.8792805075645447
Epoch: 2 Loss: 0.6232803463935852
Epoch: 3 Loss: 0.49204251170158386
Epoch: 4 Loss: 0.41875550150871277
Epoch: 5 Loss: 0.3714602589607239
Epoch: 6 Loss: 0.3378066420555115
Epoch: 7 Loss: 0.3123134672641754
Epoch: 8 Loss: 0.2921522259712219
Epoch: 9 Loss: 0.2756984531879425
Epoch: 10 Loss: 0.26194465160369873
Epoch: 11 Loss: 0.25022876262664795
Epoch: 12 Loss: 0.2400956153869629
Epoch: 13 Loss: 0.23122073709964752
Epoch: 14 Loss: 0.22336585819721222
Epoch: 15 Loss: 0.21635133028030396
Epoch: 16 Loss: 0.21003912389278412
Epoch: 17 Loss: 0.20432092249393463
Epoch: 18 Loss: 0.1991104781627655
Epoch: 19 Loss: 0.19433808326721191
Epoch: 20 Loss: 0.1899467408657074
Epoch: 21 Loss: 0.18588928878307343
Epoch: 22 Loss: 0.18212638795375824
Epoch: 23 Loss: 0.1786247193813324
Epoch: 24 Loss: 0.17535611987113953
Epoch: 25 Loss: 0.172296404838562


Evaluation of model


In [64]:
model.linear.bias

Parameter containing:
tensor([-0.1243], requires_grad=True)

In [65]:

#model evlaluation
with torch.no_grad():
  y_pred = model.forward(X_test_tensor.float())
  y_pred = (y_pred > 0.5).float()

  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f"Accuracy: {accuracy}")

Accuracy: 0.5443213582038879


# Pytorch NN Module

In [ ]:
#create model class
import torch
import torch.nn as nn

class Model(nn.Module):

  def __init__(self, num_features):
    super().__init__()

    self.network = nn.Sequential(
        nn.Linear(num_features,3),
        nn.ReLU(),
        nn.Linear(3,1),
        nn.Sigmoid()
    )
    # self.linear1 = nn.Linear(num_features,3)
    # self.relu = nn.ReLU()
    # self.linear2 = nn.Linear(3,1)
    # self.sigmoid = nn.Sigmoid()

  def forward(self, features):
    out = self.network(features)
    # out = self.linear1(features)
    # out = self.relu(out)
    # out = self.linear2(out)
    # out = self.sigmoid(out)
    return out

In [ ]:
#create a dataset
features = torch.rand(10,5)

#create model
model = Model(features.shape[1])

#call model for forward pass

model(features)         ## works directly as model.forward(features)


tensor([[0.5166],
        [0.4722],
        [0.4880],
        [0.4974],
        [0.4777],
        [0.5133],
        [0.5188],
        [0.4801],
        [0.4670],
        [0.4723]], grad_fn=<SigmoidBackward0>)

In [ ]:
#model weights
model.network

Sequential(
  (0): Linear(in_features=5, out_features=3, bias=True)
  (1): ReLU()
  (2): Linear(in_features=3, out_features=1, bias=True)
  (3): Sigmoid()
)

In [ ]:
!pip install torchinfo

In [ ]:
from torchinfo import summary

summary(model, input_size = (10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Sequential: 1-1                        [10, 1]                   --
│    └─Linear: 2-1                       [10, 3]                   18
│    └─ReLU: 2-2                         [10, 3]                   --
│    └─Linear: 2-3                       [10, 1]                   4
│    └─Sigmoid: 2-4                      [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (M): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00